sudo: false
language: node_js
node_js: stable
notifications:
  email: true
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm test
after_success:
  - npm run build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/